apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "arc-news-agent"
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - PruneLast=true
      - FailOnSharedResource=true
      - ApplyOutOfSyncOnly=true
  sources:
  - repoURL: oci://ghcr.io/lmos-ai/arc-news-agent-chart
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: lmos-demo
