apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "lmos-runtime"
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: lmos-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - PruneLast=true
      - FailOnSharedResource=true
      - ApplyOutOfSyncOnly=true
  source:
    chart: lmos-runtime-chart
    repoURL: ghcr.io/lmos-ai
    targetRevision: 0.5.0
  destination:
    server: https://kubernetes.default.svc
    namespace: lmos-demo
