# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: channel-rollout
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: lmos-operator
      app.kubernetes.io/name: lmos-operator
  template:
    metadata:
      labels:
        app: lmos-operator
        app.kubernetes.io/instance: lmos-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: lmos-operator
        app.kubernetes.io/version: 0.0.4-SNAPSHOT
        helm.sh/chart: lmos-operator-chart-0.0.4-SNAPSHOT
        version: 0.0.4-SNAPSHOT
    spec:
      containers:
      - name: lmos-operator-chart
        image: ghcr.io/lmos-ai/lmos-operator:0.0.4-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources: {}
        securityContext: {}
      imagePullSecrets:
      - name: docker-secrets
      serviceAccountName: lmos-operator
      terminationGracePeriodSeconds: 30
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: lmos-operator-vsvc.default.svc.cluster.local        # required
            routes:
            - primary                 # optional if there is a single route in VirtualService, required otherwise
          destinationRule:
            name: lmos-operator-destrule    # required
            canarySubsetName: canary  # required
            stableSubsetName: stable  # required
      steps:
      - setWeight: 5
      - pause:
          duration: 10m      

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: lmos-operator-destrule
spec:
  host: lmos-operator.default.svc.cluster.local
  subsets:
  - name: canary   # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    labels:        # labels will be injected 
      app: lmos-operator
  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    labels:        # labels will be injected 
      app: lmos-operator

---

apiVersion: v1
kind: Service
metadata:
  name: lmos-operator
spec:
  selector:
    app.kubernetes.io/instance: lmos-operator
    app.kubernetes.io/name: lmos-operator
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lmos-operator-vsvc
spec:
  hosts:
  - lmos-operator.default.svc.cluster.local
  http:
  - name: primary  # referenced in canary.trafficRouting.istio.virtualService.routes
    route:
    - destination:
        host: lmos-operator.default.svc.cluster.local
        subset: stable
        port:
          number: 8080
      weight: 100
      headers:
        request:
          set:
            x-subset: "stable"
    - destination:
        host: lmos-operator.default.svc.cluster.local
        subset: canary
        port:
          number: 8080
      weight: 0
      headers:
        request:
          set:
            x-subset: "canary"