# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: lmos-operator
  namespace: default
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: lmos-operator
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: lmos-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: lmos-operator
    app.kubernetes.io/version: 0.0.4-SNAPSHOT
    helm.sh/chart: lmos-operator-chart-0.0.4-SNAPSHOT
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: lmos-operator
      app.kubernetes.io/name: lmos-operator
  template:
    metadata:
      labels:
        app: lmos-operator
        app.kubernetes.io/instance: lmos-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: lmos-operator
        app.kubernetes.io/version: 0.0.4-SNAPSHOT
        helm.sh/chart: lmos-operator-chart-0.0.4-SNAPSHOT
        version: 0.0.4-SNAPSHOT
    spec:
      containers:
      - name: lmos-operator-chart
        image: ghcr.io/lmos-ai/lmos-operator:0.0.4-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources: {}
        securityContext: {}
      imagePullSecrets:
      - name: docker-secrets
      serviceAccountName: lmos-operator
      terminationGracePeriodSeconds: 30
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 50
      - pause: {duration: 10}
      - setWeight: 100